using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using EasiPosStock.Permissions;
using EasiPosStock.CostCentres;

namespace EasiPosStock.CostCentres
{
    public class CostCentresAppService : CostCentresAppServiceBase, ICostCentresAppService
    {
        //<suite-custom-code-autogenerated>
        public CostCentresAppService(ICostCentreRepository costCentreRepository, CostCentreManager costCentreManager)
            : base(costCentreRepository, costCentreManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}