using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using EasiPosStock.Permissions;
using EasiPosStock.Products;

namespace EasiPosStock.Products
{
    public class ProductsAppService : ProductsAppServiceBase, IProductsAppService
    {
        //<suite-custom-code-autogenerated>
        public ProductsAppService(IProductRepository productRepository, ProductManager productManager)
            : base(productRepository, productManager)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}